export interface FullPersonInfo {
    version: number;
    person: {
        email: string;
        phone: string;
        residenceCountry: string;
        citizenship: string;
        language: null | string;
        bankaccount: string;
        address: string;
        postcode: null | string;
        addressAds: string;
        addressAdsOid: string;
        firstname: string;
        lastname: string;
        fullname: string;
        idcode: string;
        sex: string;
        birthdate: string;
    };
    studyLanguage: string;
    curriculumSpeciality: null | string;
    speciality: null | string;
    addSpecialityEt: null | string;
    addSpecialityEn: null | string;
    curriculumStudyField: null | string;
    nominalStudyEnd: string;
    finSpecific: string;
    schoolEmail: string;
    previousStudyLevel: string;
    studyCompany: null | string;
    previousSchoolName: string;
    previousSchoolEndDate: string;
    dormitory: string;
    secondarySchoolCountry: null | string;
    isSpecialNeed: boolean;
    specialNeed: null | string;
    specialNeeds: any[];
    isRepresentativeMandatory: boolean;
    photo: {
        version: number;
        fdata: string;
        fname: string;
        ftype: string;
    };
    deleteCurrentPhoto: null | any;
    job: null | any;
    jobOccupation: null | any;
    otherContact: null | any;
    isAcadStudyAllowed: boolean;
    representativeOtherContact: null | any;
    studentLanguages: any[];
    occupationCertificates: any[];
    minorSpecialities: null | any;
    id: number;
    school: {
        id: number;
        nameEt: string;
        nameEn: string;
        nameRu: string;
    };
    status: string;
    curriculum: number;
    curriculumVersion: {
        id: number;
        nameEt: string;
        nameEn: string;
        code: string;
        curriculum: number;
        schoolDepartment: null | any;
        studyForm: null | any;
        isVocational: boolean;
        isHigher: boolean;
        isSecondary: boolean;
        isBasic: boolean;
        isFictive: null | any;
        studyLang: null | any;
        specialities: null | any;
        studyField: null | any;
        nameRu: string;
    };
    curriculumObject: {
        id: number;
        nameEt: string;
        nameEn: string;
        nameRu: string;
    };
    studentGroup: {
        id: number;
        nameEt: string;
        nameEn: string;
        nameRu: string;
    };
    course: number;
    studentCard: null | any;
    studentCardStatus: string;
    studentCardValidThru: null | any;
    studentCardGivenDt: null | any;
    studentCardReturnedDt: null | any;
    isStudentCardRepetitive: null | any;
    studyStart: string;
    studyEnd: null | any;
    studyForm: string;
    studyLoad: string;
    studyLevel: string;
    fin: string;
    isHigher: boolean;
    isVocational: boolean;
    isBasic: boolean;
    isSecondary: boolean;
    userCanEditStudent: boolean;
    userCanAddRepresentative: boolean;
    userIsStudentGroupTeacher: boolean;
    userCanViewStudentSpecificData: boolean;
    userCanUpdateRR: boolean;
    userCanRequestPhotoBoxPhoto: boolean;
    userCanViewStudentSupportServices: boolean;
    userCanViewPrivateStudentSupportServices: boolean;
    userCanViewStudentAddInfo: boolean;
    studentCanAddPhoto: boolean;
    isGuestStudent: boolean;
    curriculumCredits: number;
    credits: number;
    averageMark: number;
    apelApplicationCredits: number;
    isCurriculumFulfilled: boolean;
    curriculumIncludesSpecialities: boolean;
    hasRemarksPastSevenDays: boolean;
    individualCurriculum: boolean;
    individualCurriculumStart: null | any;
    individualCurriculumEnd: null | any;
    boardingSchool: null | any;
    boardingSchoolValidFrom: null | any;
    boardingSchoolValidThru: null | any;
    boardingSchoolAddInfo: null | any;
    type: string;
    fulfillmentPercentage: number;
    addInfo: null | any;
    regNr: number;
    whiteCertificate: null | any;
    dormitoryHistory: {
        date: string;
        dormitory: string;
    };
}
